### ISSUE TITLE
Milestone build default tinkerbots models

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/robot-designer#22]
The current version of the robot designer is very close to allow to build all the default models.
But there are a couple of issues with the slots that prevents it:
* [ ] missing slots definition for `cubie_box_with_round_slots`
* [ ] translation step is too big for the front face of the `cubie_box_with_round_slots` and `cubie_box_with_cross_slots` -> it is not possible to move the attached part precisely to the wanted position

Additionally:
* [ ] it should be possible to define multiple slot type for round female slots: they can be connect with both cross and round male parts
